<a href="https://colab.research.google.com/github/Runa-w/Python_for_Data_Sci/blob/master/ExercisesInPythonForDataScience_Ch7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
orders_2022_02_04 = [
 (9423517, '2021-08-04', 9001),
 (4626232, '2021-08-04', 9003),
 (9423534, '2021-08-04', 9001)
]
orders_2022_02_05 = [
 (9423679, '2021-08-05', 9002),
 (4626377, '2021-08-05', 9003),
 (4626412, '2021-08-05', 9004)
]
orders_2022_02_06 = [
 (9423783, '2021-08-06', 9002),
 (4626490, '2021-08-06', 9004)
]

orders = orders_2022_02_04 + orders_2022_02_05 + orders_2022_02_06

print(orders)

[(9423517, '2021-08-04', 9001), (4626232, '2021-08-04', 9003), (9423534, '2021-08-04', 9001), (9423679, '2021-08-05', 9002), (4626377, '2021-08-05', 9003), (4626412, '2021-08-05', 9004), (9423783, '2021-08-06', 9002), (4626490, '2021-08-06', 9004)]


In [ ]:
extra_fields_9423517 = {
    'ShippingInstrustions' : { 'name' : 'John Silver', 'Phone' : [{ 'type' : 'Office', 'number' : '809-123-9309'}, { 'type' : 'Mobile', 'number' : '417-123-4567'}]}
}

order_9423517 = {'OrderNo':9423517, 'Date':'2022-02-04', 'Empno':9001}

order_9423517 = {**order_9423517, **extra_fields_9423517}

print(order_9423517)

{'OrderNo': 9423517, 'Date': '2022-02-04', 'Empno': 9001, 'ShippingInstrustions': {'name': 'John Silver', 'Phone': [{'type': 'Office', 'number': '809-123-9309'}, {'type': 'Mobile', 'number': '417-123-4567'}]}}


In [ ]:
details = [
 (9423517, 'Jeans', 'Rip Curl', 87.0, 1),
 (9423517, 'Jacket', 'The North Face', 112.0, 1),
 (4626232, 'Socks', 'Vans', 15.0, 1),
 (4626232, 'Jeans', 'Quiksilver', 82.0, 1),
 (9423534, 'Socks', 'DC', 10.0, 2),
 (9423534, 'Socks', 'Quiksilver', 12.0, 2),
 (9423679, 'T-shirt', 'Patagonia', 35.0, 1),
 (4626377, 'Hoody', 'Animal', 44.0, 1),
 (4626377, 'Cargo Shorts', 'Animal', 38.0, 1),
 (4626412, 'Shirt', 'Volcom', 78.0, 1),
 (9423783, 'Boxer Shorts', 'Superdry', 30.0, 2),
 (9423783, 'Shorts', 'Globe', 26.0, 1),
 (4626490, 'Cargo Shorts', 'Billabong', 54.0, 1),
 (4626490, 'Sweater', 'Dickies', 56.0, 1)
]

order_details = [[o for o in orders if d[0] == o[0]][0] + d[1:] for d in details]

print(order_details)

[(9423517, '2021-08-04', 9001, 'Jeans', 'Rip Curl', 87.0, 1), (9423517, '2021-08-04', 9001, 'Jacket', 'The North Face', 112.0, 1), (4626232, '2021-08-04', 9003, 'Socks', 'Vans', 15.0, 1), (4626232, '2021-08-04', 9003, 'Jeans', 'Quiksilver', 82.0, 1), (9423534, '2021-08-04', 9001, 'Socks', 'DC', 10.0, 2), (9423534, '2021-08-04', 9001, 'Socks', 'Quiksilver', 12.0, 2), (9423679, '2021-08-05', 9002, 'T-shirt', 'Patagonia', 35.0, 1), (4626377, '2021-08-05', 9003, 'Hoody', 'Animal', 44.0, 1), (4626377, '2021-08-05', 9003, 'Cargo Shorts', 'Animal', 38.0, 1), (4626412, '2021-08-05', 9004, 'Shirt', 'Volcom', 78.0, 1), (9423783, '2021-08-06', 9002, 'Boxer Shorts', 'Superdry', 30.0, 2), (9423783, '2021-08-06', 9002, 'Shorts', 'Globe', 26.0, 1), (4626490, '2021-08-06', 9004, 'Cargo Shorts', 'Billabong', 54.0, 1), (4626490, '2021-08-06', 9004, 'Sweater', 'Dickies', 56.0, 1)]


In [ ]:
details.append((4626592, 'Shorts', 'Protest', 48.0, 1))

order_details_right = [[o for o in orders if d[0] in o][0] + d[1:] if d[0] in [o[0] for o in orders] else (d[0], None, None) + d[1:] for d in details]
sum(pr*qt for _, _, _, _, _, pr, qt in order_details_right)

779.0

In [ ]:
import numpy as np
jeff_salary = [2700, 3000, 3000]
nick_salary = [2600, 2800, 2800]
tom_salary = [2300, 2500, 2500]
base_salary1 = np.array([jeff_salary, nick_salary, tom_salary])

maya_salary = [2200, 2400, 2400]
john_salary = [2500, 2700, 2700]
base_salary2 = np.array([maya_salary, john_salary])

base_salary = np.concatenate((base_salary1, base_salary2), axis = 0)

print(base_salary)

[[2700 3000 3000]
 [2600 2800 2800]
 [2300 2500 2500]
 [2200 2400 2400]
 [2500 2700 2700]]


In [ ]:
new_month_salary = np.array([[3000],[2900],[2500],[3500],[2700]])
print(new_month_salary)

[[3000]
 [2900]
 [2500]
 [3500]
 [2700]]


In [ ]:
base_salary = np.concatenate((base_salary, new_month_salary), axis=1)
print(base_salary)

[[2700 3000 3000 3000]
 [2600 2800 2800 2900]
 [2300 2500 2500 2500]
 [2200 2400 2400 3500]
 [2500 2700 2700 2700]]


In [ ]:
import pandas as pd
salary_df1 = pd.DataFrame(
    {'jeff': jeff_salary,
     'nick': nick_salary,
     'tom': tom_salary}
)

salary_df1.index = ['June', 'July', 'August']
print(salary_df1
)

        jeff  nick   tom
June    2700  2600  2300
July    3000  2800  2500
August  3000  2800  2500


In [ ]:
salary_df1 = salary_df1.transpose()
print(salary_df1)

      June  July  August
jeff  2700  3000    3000
nick  2600  2800    2800
tom   2300  2500    2500


In [ ]:
salary_df2 = pd.DataFrame(
    {'maya': maya_salary,
     'john': john_salary},
    index = ['June', 'July', 'August']
).transpose()
print(salary_df2)

      June  July  August
maya  2200  2400    2400
john  2500  2700    2700


In [ ]:
salary_df = pd.concat([salary_df1, salary_df2])
print(salary_df)

      June  July  August
jeff  2700  3000    3000
nick  2600  2800    2800
tom   2300  2500    2500
maya  2200  2400    2400
john  2500  2700    2700


In [ ]:
salary_df3 = pd.DataFrame(
    {'September': [3000,2800,2500,2400,2700],
     'October': [3200,3000,2700,2500,2900]},
    index = ['jeff', 'nick', 'tom', 'maya', 'john']
)

salary_df = pd.concat([salary_df, salary_df3], axis=1)

print(salary_df)

      June  July  August  September  October
jeff  2700  3000    3000       3000     3200
nick  2600  2800    2800       2800     3000
tom   2300  2500    2500       2500     2700
maya  2200  2400    2400       2400     2500
john  2500  2700    2700       2700     2900


In [ ]:
salary_df = salary_df.drop(['September', 'October'], axis=1)
print(salary_df)

      June  July  August
jeff  2700  3000    3000
nick  2600  2800    2800
tom   2300  2500    2500
maya  2200  2400    2400
john  2500  2700    2700


In [ ]:
salary_df = salary_df.drop(['nick', 'maya'], axis=0)
print(salary_df)

      June  July  August
jeff  2700  3000    3000
tom   2300  2500    2500
john  2500  2700    2700


In [ ]:
df_date_region1 = pd.DataFrame(
    [
        ('2022-02-04', 'East', 97.0),
        ('2022-02-04', 'West', 243.0),
        ('2022-02-05', 'East', 160.0),
        ('2022-02-05', 'West', 35.0),
        ('2022-02-06', 'East', 110.0),
        ('2022-02-06', 'West', 86.0)
    ],
    columns=['Date', 'Region', 'Total']).set_index(['Date', 'Region'])

df_date_region2 = pd.DataFrame(
    [
        ('2022-02-04', 'South', 114.0),
        ('2022-02-05', 'South', 325.0),
        ('2022-02-06', 'South', 212.0)
    ],
    columns=['Date', 'Region', 'Total']).set_index(['Date', 'Region'])

df_date_region = pd.concat([df_date_region1, df_date_region2]).sort_index(level=['Date', 'Region'])

print(df_date_region)

                   Total
Date       Region       
2022-02-04 East     97.0
           South   114.0
           West    243.0
2022-02-05 East    160.0
           South   325.0
           West     35.0
2022-02-06 East    110.0
           South   212.0
           West     86.0


In [ ]:
import pandas as pd
df_orders = pd.DataFrame(orders, columns =['OrderNo', 'Date', 'Empco'])
df_details = pd.DataFrame(details, columns = ['OrderNo', 'Item', 'Brand','Price', 'Quantity'])

In [ ]:
df_details = df_details.append(
    {'OrderNo': 4626592,
     'Item': 'Shorts',
     'Brand': 'Protest',
     'Price': 48.0,
     'Quantity': 1
     },
    ignore_index = True
)

df_orders_details_right = df_orders.merge(df_details, how='right', left_on='OrderNo', right_on='OrderNo')
print(df_orders_details_right )

    OrderNo        Date   Empco          Item           Brand  Price  Quantity
0   9423517  2021-08-04  9001.0         Jeans        Rip Curl   87.0         1
1   9423517  2021-08-04  9001.0        Jacket  The North Face  112.0         1
2   4626232  2021-08-04  9003.0         Socks            Vans   15.0         1
3   4626232  2021-08-04  9003.0         Jeans      Quiksilver   82.0         1
4   9423534  2021-08-04  9001.0         Socks              DC   10.0         2
5   9423534  2021-08-04  9001.0         Socks      Quiksilver   12.0         2
6   9423679  2021-08-05  9002.0       T-shirt       Patagonia   35.0         1
7   4626377  2021-08-05  9003.0         Hoody          Animal   44.0         1
8   4626377  2021-08-05  9003.0  Cargo Shorts          Animal   38.0         1
9   4626412  2021-08-05  9004.0         Shirt          Volcom   78.0         1
10  9423783  2021-08-06  9002.0  Boxer Shorts        Superdry   30.0         2
11  9423783  2021-08-06  9002.0        Shorts       

<ipython-input-22-09fdb7bf3dc8>:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_details = df_details.append(


In [ ]:
df_orders_details_right = df_orders_details_right.fillna({'Empno':0}).astype({'Empno':'int64'})
print(df_orders_details_right)

KeyError: ignored