<a href="https://colab.research.google.com/github/Runa-w/Python_for_Data_Sci/blob/master/ExercisesForPythonForDataScience_Ch1_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

The following are exercises and examples from Chapter 2 of Python for Data Science by Yuli Vasiliev.

In [ ]:
my_list = []

my_list.append('Pay bills')
my_list.append('Tidy up')
my_list.append('Walk the dog')
my_list.append('Cook dinner')

In [ ]:
print(my_list)

['Pay bills', 'Tidy up', 'Walk the dog', 'Cook dinner']


In [ ]:
print(my_list[0])

Pay bills


In [ ]:
i = my_list.index('Cook dinner')

my_list.insert(i, 'Go to the pharmacy')

print(my_list)

['Pay bills', 'Tidy up', 'Walk the dog', 'Go to the pharmacy', 'Cook dinner']


In [ ]:
print(my_list.count('Tidy up'))

1


In [ ]:
print(my_list[0:3])

['Pay bills', 'Tidy up', 'Walk the dog']


In [ ]:
my_list[len(my_list):] = ['Mow the lawn', 'Water Plants']
print(my_list)

['Pay bills', 'Tidy up', 'Walk the dog', 'Go to the pharmacy', 'Cook dinner', 'Mow the lawn', 'Water Plants']


In [ ]:
del my_list[5:]
print(my_list)

['Pay bills', 'Tidy up', 'Walk the dog', 'Go to the pharmacy', 'Cook dinner']


In [ ]:
from collections import deque
queue = deque(my_list)
queue.append('Wash the Car')
print(queue.popleft(), ' - Done!')
my_list_upd = list(queue)

Pay bills  - Done!


In [ ]:
print(my_list)
print(my_list_upd)

['Pay bills', 'Tidy up', 'Walk the dog', 'Go to the pharmacy', 'Cook dinner']
['Tidy up', 'Walk the dog', 'Go to the pharmacy', 'Cook dinner', 'Wash the Car']


In [ ]:
stack = []
for task in my_list:
  stack.append(task)
while stack:
  print(stack.pop(), ' - Done!')
print('\nThe stack is empty')

Cook dinner  - Done!
Go to the pharmacy  - Done!
Walk the dog  - Done!
Tidy up  - Done!
Pay bills  - Done!

The stack is empty


In [ ]:
txt = '''Python is one of the most promising programming languages today. Due to the simplicity of Python syntax, many researchers and scientists prefer Python over many other languages.'''

txt = txt.replace('.', '').replace(',', '')
lst = txt.split()
print(lst)

['Python', 'is', 'one', 'of', 'the', 'most', 'promising', 'programming', 'languages', 'today', 'Due', 'to', 'the', 'simplicity', 'of', 'Python', 'syntax', 'many', 'researchers', 'and', 'scientists', 'prefer', 'Python', 'over', 'many', 'other', 'languages']


In [ ]:
dct = {}
for w in lst:
  c = dct.setdefault(w,0)
  dct[w] += 1

dct_sorted = dict(sorted(dct.items(), key=lambda x: x[1], reverse=True))
print(dct_sorted)

{'Python': 3, 'of': 2, 'the': 2, 'languages': 2, 'many': 2, 'is': 1, 'one': 1, 'most': 1, 'promising': 1, 'programming': 1, 'today': 1, 'Due': 1, 'to': 1, 'simplicity': 1, 'syntax': 1, 'researchers': 1, 'and': 1, 'scientists': 1, 'prefer': 1, 'over': 1, 'other': 1}


In [ ]:
l = [
    {
        'name' : 'photo1.jpg',
        'tags' : {'coffee', 'breakfast', 'drink', 'table', 'tableware', 'cup', 'food'}
    },
    {
        'name' : 'photo2.jpg',
        'tags' : {'food', 'dish', 'meat', 'meal', 'tableware', 'dinner', 'vegetable'}
    },
    {
        'name' : 'photo3.jpg'
        'tags' : {'city', 'skyline', 'cityscape', 'skyscraper', 'architecture', 'building', 'travel'}
    },
    {
        'name' : 'photo4.jpg'
        'tags' : {'drink', 'juice', 'glass', 'meal', 'fruit', 'food', 'grapes'}
    }
]

photo_groups = {}

for i in range(1, len(1)):
  for j in range(i + 1, len(1)+1):
    print(f"Interesting photo {i} with photo {j}")
    # Implament intersection here, saving results to photo_groups

In [ ]:
import numpy as np
jeff_salary = [2700, 3000, 3000]
nick_salary = [2600, 2800, 2800]
tom_salary = [2300, 2500, 2500]
base_salary = np.array([jeff_salary, nick_salary, tom_salary])
print(base_salary)

[[2700 3000 3000]
 [2600 2800 2800]
 [2300 2500 2500]]


In [ ]:
jeff_bonus = [500, 400, 400]
nick_bonus = [600, 300, 400]
tom_bonus = [200, 500, 400]
bonus = np.array([jeff_bonus, nick_bonus, tom_bonus])

salary_bonus = base_salary + bonus
print(type(salary_bonus))
print(salary_bonus)


<class 'numpy.ndarray'>
[[3200 3400 3400]
 [3200 3100 3200]
 [2500 3000 2900]]


In [ ]:
print(salary_bonus.max())

3400


In [ ]:
print(np.amax(salary_bonus, axis=1))

[3400 3200 3000]


In [ ]:
avg = np.amax(salary_bonus, axis=0)
print(avg)

[3200 3400 3400]


In [ ]:
print(np.average(avg))

3333.3333333333335


In [ ]:
import pandas as pd
data = ['Jeff Russell', 'James Boorman', 'Tom Heints']
emps_names = pd.Series(data, index=(9001, 9002, 9003))
print(emps_names)

9001     Jeff Russell
9002    James Boorman
9003       Tom Heints
dtype: object


In [ ]:
print(emps_names[9001])
print(emps_names.iloc[0])

Jeff Russell
Jeff Russell


In [ ]:
data = ['jeff.russell', 'jane.boorman', 'tom.heints']
phones = ['xxx-xxx-1234', 'xxx-xxx-5678', 'xxx-xxx-9101']
emps_emails = pd.Series(data, index=[9001, 9002, 9003],name = 'emails')
emps_names.name = 'names'
emps_phones = pd.Series(phones, index=[9001, 9002, 9003], name = 'phones' )
df = pd.concat([emps_names, emps_emails, emps_phones], axis=1)
print(df)

              names        emails        phones
9001   Jeff Russell  jeff.russell  xxx-xxx-1234
9002  James Boorman  jane.boorman  xxx-xxx-5678
9003     Tom Heints    tom.heints  xxx-xxx-9101


In [ ]:
import yfinance as yf
tkr = yf.Ticker('TSLA')
hist = tkr.history(period='5d')
hist = hist.drop('Dividends', axis=1)
hist = hist.drop('Stock Splits', axis = 1)
hist = hist.reset_index()
hist = hist.set_index('Date')
print(hist)

                                 Open        High         Low       Close  \
Date                                                                        
2023-11-08 00:00:00-05:00  223.149994  224.149994  217.639999  222.110001   
2023-11-09 00:00:00-05:00  219.750000  220.800003  206.679993  209.979996   
2023-11-10 00:00:00-05:00  210.029999  215.380005  205.690002  214.649994   
2023-11-13 00:00:00-05:00  215.600006  225.399994  211.610001  223.710007   
2023-11-14 00:00:00-05:00  235.029999  238.139999  230.720001  237.410004   

                              Volume  
Date                                  
2023-11-08 00:00:00-05:00  106584800  
2023-11-09 00:00:00-05:00  142110500  
2023-11-10 00:00:00-05:00  130994000  
2023-11-13 00:00:00-05:00  140447600  
2023-11-14 00:00:00-05:00  148611400  


In [4]:
import pandas as pd
df = pd.read_csv('/content/amazon_cells_labelled.txt', names=['review', 'sentiment'], sep='\t')

In [6]:
from sklearn.model_selection import train_test_split
reviews = df['review'].values
sentiments = df['sentiment'].values
reviews_train, reviews_test, sentiment_train, sentiment_test = train_test_split(reviews, sentiments, test_size=0.2, random_state=500)

In [8]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
vectorizer.fit(reviews)
X_train = vectorizer.transform(reviews_train)
X_test = vectorizer.transform(reviews_test)

from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(X_train, sentiment_train)

accuracy = classifier.score(X_test, sentiment_test)
print("Accuracy:", accuracy)

Accuracy: 0.81


In [9]:
new_reviews = ['Old version of python useless', 'Very good effort, but not five stars', 'Clear and concise']
X_new = vectorizer.transform(new_reviews)
print(classifier.predict(X_new))

[0 0 1]
